Repository Team-HMH/HMH-Server, pull requests merged in 2024-05, with the labels that each got.

#127 feat - 사용할 포인트 받기 api 추가
  src/main/java/sopt/org/hmh/domain/challenge/controller/ChallengeApi.java
  src/main/java/sopt/org/hmh/domain/challenge/controller/ChallengeController.java
  src/main/java/sopt/org/hmh/domain/challenge/dto/response/PointUsageResponse.java
  src/main/java/sopt/org/hmh/domain/challenge/repository/ChallengeRepository.java
  src/main/java/sopt/org/hmh/domain/challenge/service/ChallengeService.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/domain/DailyChallenge.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/domain/exception/DailyChallengeError.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/repository/DailyChallengeRepository.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/service/DailyChallengeService.java
  src/main/java/sopt/org/hmh/domain/point/controller/PointApi.java
  src/main/java/sopt/org/hmh/domain/point/controller/PointController.java
  src/main/java/sopt/org/hmh/domain/point/dto/response/EarnPointResponse.java
  src/main/java/sopt/org/hmh/domain/point/dto/response/UsagePointResponse.java
  src/main/java/sopt/org/hmh/domain/point/dto/response/UsePointResponse.java
  src/main/java/sopt/org/hmh/domain/point/exception/PointSuccess.java
  src/main/java/sopt/org/hmh/domain/point/service/PointFacade.java
  src/main/java/sopt/org/hmh/domain/user/domain/User.java
  src/main/java/sopt/org/hmh/domain/user/domain/UserConstants.java
  src/main/java/sopt/org/hmh/domain/user/repository/UserRepository.java
  src/main/java/sopt/org/hmh/domain/user/service/UserService.java
Labels: 🪄 API, ✨ Feat, 👨🏻‍💻 승환

#129 modify - challengeDay 20일 30일 추가
  src/main/java/sopt/org/hmh/domain/challenge/domain/ChallengeDay.java
  src/main/java/sopt/org/hmh/domain/challenge/service/ChallengeService.java
Labels: 👨🏻‍💻 승환, 🔧 Modify

#130 modify - 완료된 챌린지 정보를 리스트로 보내도록 수정
  src/main/java/sopt/org/hmh/domain/app/dto/request/AppArrayUsageTimeRequest.java
  src/main/java/sopt/org/hmh/domain/app/service/AppService.java
  src/main/java/sopt/org/hmh/domain/challenge/domain/Challenge.java
  src/main/java/sopt/org/hmh/domain/challenge/repository/ChallengeRepository.java
  src/main/java/sopt/org/hmh/domain/challenge/service/ChallengeService.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/controller/DailyChallengeApi.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/controller/DailyChallengeController.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/domain/DailyChallenge.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/domain/exception/DailyChallengeError.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/domain/exception/DailyChallengeSuccess.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/dto/request/FinishedDailyChallengeListRequest.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/dto/request/FinishedDailyChallengeRequest.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/service/DailyChallengeFacade.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/service/DailyChallengeService.java
  src/main/java/sopt/org/hmh/domain/user/domain/User.java
  src/main/java/sopt/org/hmh/domain/user/service/UserService.java
Labels: 👨🏻‍💻 승환, 🔧 Modify

#132 modify - 챌린지 생성 시 일수만큼 일별챌린지 생성되도록 수정
  src/main/java/sopt/org/hmh/domain/challenge/service/ChallengeService.java
Labels: 👩🏻‍💻 주민, 🔧 Modify, 🔥 Pull Request

#135 feat - 유저테이블에 현재 챌린지 정보 저장
  src/main/java/sopt/org/hmh/domain/challenge/service/ChallengeService.java
  src/main/java/sopt/org/hmh/domain/user/domain/User.java
Labels: ✨ Feat, 👩🏻‍💻 주민, 🔥 Pull Request

#138 feat - 챌린지 달성현황뷰 response에 챌린지 시작날짜 추가
  src/main/java/sopt/org/hmh/domain/challenge/controller/ChallengeController.java
  src/main/java/sopt/org/hmh/domain/challenge/dto/response/ChallengeResponse.java
  src/main/java/sopt/org/hmh/domain/challenge/repository/ChallengeRepository.java
  src/main/java/sopt/org/hmh/domain/challenge/service/ChallengeService.java
  src/main/java/sopt/org/hmh/domain/user/domain/exception/UserError.java
  src/main/java/sopt/org/hmh/domain/user/service/UserService.java
Labels: 👩🏻‍💻 주민, 🔧 Modify, 🔥 Pull Request

#141 modify - 앱관련 도메인 이름 ChallengeApp, HistoryApp으로 변경 및 적용
  src/main/java/sopt/org/hmh/domain/app/domain/ChallengeApp.java
  src/main/java/sopt/org/hmh/domain/app/domain/HistoryApp.java
  src/main/java/sopt/org/hmh/domain/app/dto/request/AppArrayGoalTimeRequest.java
  src/main/java/sopt/org/hmh/domain/app/dto/request/ChallengeAppArrayRequest.java
  src/main/java/sopt/org/hmh/domain/app/dto/request/ChallengeAppRequest.java
  src/main/java/sopt/org/hmh/domain/app/dto/request/HistoryAppRequest.java
  src/main/java/sopt/org/hmh/domain/app/dto/response/ChallengeAppResponse.java
  src/main/java/sopt/org/hmh/domain/app/repository/ChallengeAppRepository.java
  src/main/java/sopt/org/hmh/domain/app/repository/HistoryAppRepository.java
  src/main/java/sopt/org/hmh/domain/app/service/AppService.java
  src/main/java/sopt/org/hmh/domain/challenge/controller/ChallengeApi.java
  src/main/java/sopt/org/hmh/domain/challenge/controller/ChallengeController.java
  src/main/java/sopt/org/hmh/domain/challenge/domain/Challenge.java
  src/main/java/sopt/org/hmh/domain/challenge/dto/request/ChallengeSignUpRequest.java
  src/main/java/sopt/org/hmh/domain/challenge/dto/response/ChallengeResponse.java
  src/main/java/sopt/org/hmh/domain/challenge/dto/response/DailyChallengeResponse.java
  src/main/java/sopt/org/hmh/domain/challenge/service/ChallengeService.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/domain/DailyChallenge.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/dto/request/FinishedDailyChallengeRequest.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/service/DailyChallengeFacade.java
Labels: 👩🏻‍💻 주민, 🔧 Modify, 🔥 Pull Request

#143 feat - 포인트 수령 여부 리스트 조회 api 구현
  src/main/java/sopt/org/hmh/domain/point/controller/PointApi.java
  src/main/java/sopt/org/hmh/domain/point/controller/PointController.java
  src/main/java/sopt/org/hmh/domain/point/dto/response/ChallengePointStatusListResponse.java
  src/main/java/sopt/org/hmh/domain/point/dto/response/ChallengePointStatusResponse.java
  src/main/java/sopt/org/hmh/domain/point/dto/response/EarnPointResponse.java
  src/main/java/sopt/org/hmh/domain/point/exception/PointSuccess.java
  src/main/java/sopt/org/hmh/domain/point/service/PointFacade.java
Labels: ✨ Feat, 👩🏻‍💻 주민, 🔥 Pull Request

#146 deploy - prod 서버 CI/CD 플로우 구축
  .github/issue_template.md
  .github/workflows/hmh-cd-dev.yml
  .github/workflows/hmh-cd-prod.yml
  .github/workflows/hmh-ci.yml
Labels: 🚀 Deploy, 👨🏻‍💻 승환

#148 deploy - prod 서버를 위한 CI/CD 플로우 수정
  .github/workflows/hmh-cd-prod.yml
  .github/workflows/hmh-ci-dev.yml
  .github/workflows/hmh-ci-prod.yml
  script/start.sh
Labels: 🚀 Deploy, 👨🏻‍💻 승환

#152 fix - request의 LocalDate의 역직렬화 오류 해결
  src/main/java/sopt/org/hmh/domain/point/controller/PointApi.java
  src/main/java/sopt/org/hmh/domain/point/controller/PointController.java
  src/main/java/sopt/org/hmh/domain/point/dto/request/ChallengeDateRequest.java
Labels: 👨🏻‍💻 승환, 🐞 BugFix
