Repository Team-HMH/HMH-Server, pull requests merged in 2024-04, with the labels that each got.

#116 refactor - 챌린지 관련 도메인 수정
  src/HMH-Server.iml
  src/main/java/sopt/org/hmh/domain/app/controller/AppApi.java
  src/main/java/sopt/org/hmh/domain/app/controller/AppController.java
  src/main/java/sopt/org/hmh/domain/app/domain/App.java
  src/main/java/sopt/org/hmh/domain/app/domain/AppWithGoalTime.java
  src/main/java/sopt/org/hmh/domain/app/domain/AppWithUsageGoalTime.java
  src/main/java/sopt/org/hmh/domain/app/domain/exception/AppSuccess.java
  src/main/java/sopt/org/hmh/domain/app/dto/request/AppRemoveRequest.java
  src/main/java/sopt/org/hmh/domain/app/repository/AppRepository.java
  src/main/java/sopt/org/hmh/domain/app/repository/AppWithGoalTimeRepository.java
  src/main/java/sopt/org/hmh/domain/app/repository/AppWithUsageGoalTimeRepository.java
  src/main/java/sopt/org/hmh/domain/app/service/AppService.java
  src/main/java/sopt/org/hmh/domain/auth/service/AuthService.java
  src/main/java/sopt/org/hmh/domain/challenge/controller/ChallengeApi.java
  src/main/java/sopt/org/hmh/domain/challenge/controller/ChallengeController.java
  src/main/java/sopt/org/hmh/domain/challenge/domain/Challenge.java
  src/main/java/sopt/org/hmh/domain/challenge/domain/exception/ChallengeSuccess.java
  src/main/java/sopt/org/hmh/domain/challenge/dto/response/ChallengeResponse.java
  src/main/java/sopt/org/hmh/domain/challenge/dto/response/DailyChallengeResponse.java
  src/main/java/sopt/org/hmh/domain/challenge/service/ChallengeService.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/controller/DailyChallengeApi.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/controller/DailyChallengeController.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/domain/DailyChallenge.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/domain/exception/DailyChallengeSuccess.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/dto/response/DailyChallengeResponse.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/service/DailyChallengeService.java
Labels: 👩🏻‍💻 주민, 🔥 Pull Request, 🔨 Refactor

#118 fix: test 실패 해결 및 users 패키지 네이밍 user로 변경
  build.gradle
  src/main/java/sopt/org/hmh/domain/auth/dto/response/LoginResponse.java
  src/main/java/sopt/org/hmh/domain/auth/repository/OnboardingInfoRepository.java
  src/main/java/sopt/org/hmh/domain/auth/repository/ProblemRepository.java
  src/main/java/sopt/org/hmh/domain/auth/service/AuthService.java
  src/main/java/sopt/org/hmh/domain/user/controller/UserApi.java
  src/main/java/sopt/org/hmh/domain/user/controller/UserController.java
  src/main/java/sopt/org/hmh/domain/user/domain/OnboardingInfo.java
  src/main/java/sopt/org/hmh/domain/user/domain/OnboardingProblem.java
  src/main/java/sopt/org/hmh/domain/user/domain/User.java
  src/main/java/sopt/org/hmh/domain/user/domain/UserConstants.java
  src/main/java/sopt/org/hmh/domain/user/domain/exception/UserError.java
  src/main/java/sopt/org/hmh/domain/user/domain/exception/UserException.java
  src/main/java/sopt/org/hmh/domain/user/domain/exception/UserSuccess.java
  src/main/java/sopt/org/hmh/domain/user/dto/response/UserInfoResponse.java
  src/main/java/sopt/org/hmh/domain/user/repository/UserRepository.java
  src/main/java/sopt/org/hmh/domain/user/service/ExpiredUserDeleteScheduler.java
  src/main/java/sopt/org/hmh/domain/user/service/UserService.java
  src/main/java/sopt/org/hmh/global/auth/social/kakao/fegin/KakaoLoginService.java
  src/test/java/sopt/org/hmh/HmhApplicationTests.java
Labels: 🚀 Deploy, 👨🏻‍💻 승환, 🐞 BugFix

#119 feat: 포인트 사용 api 구현
  src/main/java/sopt/org/hmh/domain/challenge/controller/ChallengeApi.java
  src/main/java/sopt/org/hmh/domain/challenge/controller/ChallengeController.java
  src/main/java/sopt/org/hmh/domain/challenge/domain/Challenge.java
  src/main/java/sopt/org/hmh/domain/challenge/domain/ChallengeConstants.java
  src/main/java/sopt/org/hmh/domain/challenge/domain/exception/ChallengeError.java
  src/main/java/sopt/org/hmh/domain/challenge/dto/response/PointUsageResponse.java
  src/main/java/sopt/org/hmh/domain/challenge/service/ChallengeService.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/controller/DailyChallengeApi.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/controller/DailyChallengeController.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/domain/DailyChallenge.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/repository/DailyChallengeRepository.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/service/DailyChallengeService.java
  src/main/java/sopt/org/hmh/domain/user/domain/User.java
  src/main/java/sopt/org/hmh/domain/user/domain/exception/UserError.java
Labels: ✨ Feat, 👨🏻‍💻 승환, 🔥 Pull Request
