Repository Team-HMH/HMH-Server, pull requests merged in 2024-02, with the labels that each got.

#96 feat - 회원 탈퇴 시에 리프레시 토큰 삭제
  src/main/java/sopt/org/HMH/domain/user/service/UserService.java
Labels: ✨ Feat, 👨🏻‍💻 승환, 🔥 Pull Request

#98 fix -자정 챌린지 정보 업데이트 로직 수정
  src/main/java/sopt/org/HMH/domain/dailychallenge/domain/exception/DailyChallengeError.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/domain/exception/DailyChallengeSuccess.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/service/DailyChallengeService.java
Labels: 👩🏻‍💻 주민, 🐞 BugFix, 🔥 Pull Request

#99 fix - 중복된 유저 회원가입 되지 않도록 수정
  src/main/java/sopt/org/HMH/domain/user/domain/User.java
Labels: ☁️ Database, 👨🏻‍💻 승환, 🐞 BugFix, 🔥 Pull Request
