Repository Team-HMH/HMH-Server, pull requests merged in 2024-01, with the labels that each got.

#5 feat - 예외 핸들링 클래스 구현 및 공통 응답 클래스 구현
  .gitignore
  src/main/java/sopt/org/HMH/HmhApplication.java
  src/main/java/sopt/org/HMH/common/config/JpaAuditingConfig.java
  src/main/java/sopt/org/HMH/common/domain/BaseTimeEntity.java
  src/main/java/sopt/org/HMH/common/exception/GlobalError.java
  src/main/java/sopt/org/HMH/common/exception/GlobalException.java
  src/main/java/sopt/org/HMH/common/exception/GlobalSuccess.java
  src/main/java/sopt/org/HMH/common/exception/base/ErrorBase.java
  src/main/java/sopt/org/HMH/common/exception/base/ExceptionBase.java
  src/main/java/sopt/org/HMH/common/exception/base/RootEnum.java
  src/main/java/sopt/org/HMH/common/exception/base/SuccessBase.java
  src/main/java/sopt/org/HMH/common/response/ApiResponse.java
  src/main/java/sopt/org/HMH/common/response/CommonControllerAdvice.java
Labels: ✨ Feat, 👨🏻‍💻 승환, 🔥 Pull Request

#6 feat - CI / CD 세팅과 배포 테스트
  .github/workflows/hmh-cd.yml
  .github/workflows/hmh-ci.yml
  appspec.yml
  script/start.sh
  script/stop.sh
  src/main/java/sopt/org/HMH/HealthCheckApiController.java
Labels: 🚀 Deploy, 👨🏻‍💻 승환, 🔥 Pull Request

#8 deploy - 배포 테스트를 위한 main 브랜치에 push
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .github/workflows/hmh-cd.yml
  .github/workflows/hmh-ci.yml
Labels: 🚀 Deploy, 👨🏻‍💻 승환, 🔥 Pull Request

#12 fix - CD 에러 해결
  .github/workflows/hmh-cd.yml
  .github/workflows/hmh-ci.yml
  build.gradle
  script/start.sh
Labels: 🚀 Deploy, 👨🏻‍💻 승환, 🔥 Pull Request

#17 feat - 카카오 로그인 기능 구현
  .gitignore
  build.gradle
  src/main/java/sopt/org/HMH/HealthCheckApiController.java
  src/main/java/sopt/org/HMH/HmhApplication.java
  src/main/java/sopt/org/HMH/domain/app/controller/AppController.java
  src/main/java/sopt/org/HMH/domain/app/domain/App.java
  src/main/java/sopt/org/HMH/domain/app/dto/request/AppGoalTimeRequest.java
  src/main/java/sopt/org/HMH/domain/app/repository/AppRepository.java
  src/main/java/sopt/org/HMH/domain/app/service/AppService.java
  src/main/java/sopt/org/HMH/domain/challenge/controller/ChallengeController.java
  src/main/java/sopt/org/HMH/domain/challenge/domain/Challenge.java
  src/main/java/sopt/org/HMH/domain/challenge/domain/exception/ChallengeSuccess.java
  src/main/java/sopt/org/HMH/domain/challenge/dto/request/ChallengeRequest.java
  src/main/java/sopt/org/HMH/domain/challenge/repository/ChallengeRepository.java
  src/main/java/sopt/org/HMH/domain/challenge/service/ChallengeService.java
  src/main/java/sopt/org/HMH/domain/dayChallenge/domain/DayChallenge.java
  src/main/java/sopt/org/HMH/domain/dayChallenge/domain/exception/DayChallengeError.java
  src/main/java/sopt/org/HMH/domain/dayChallenge/repository/DayChallengeRepository.java
  src/main/java/sopt/org/HMH/domain/dayChallenge/service/DayChallengeService.java
  src/main/java/sopt/org/HMH/domain/user/User.java
  src/main/java/sopt/org/HMH/domain/user/controller/UserController.java
  src/main/java/sopt/org/HMH/domain/user/domain/User.java
  src/main/java/sopt/org/HMH/domain/user/domain/exception/UserError.java
  src/main/java/sopt/org/HMH/domain/user/domain/exception/UserException.java
  src/main/java/sopt/org/HMH/domain/user/domain/exception/UserSuccess.java
  src/main/java/sopt/org/HMH/domain/user/dto/request/SocialLoginRequest.java
  src/main/java/sopt/org/HMH/domain/user/dto/response/LoginResponse.java
  src/main/java/sopt/org/HMH/domain/user/repository/UserRepository.java
  src/main/java/sopt/org/HMH/domain/user/service/UserService.java
  src/main/java/sopt/org/HMH/global/auth/jwt/JwtProvider.java
  src/main/java/sopt/org/HMH/global/auth/jwt/JwtValidationType.java
  src/main/java/sopt/org/HMH/global/auth/jwt/TokenDto.java
  src/main/java/sopt/org/HMH/global/auth/jwt/exception/JwtError.java
  src/main/java/sopt/org/HMH/global/auth/jwt/exception/JwtException.java
  src/main/java/sopt/org/HMH/global/auth/redis/RefreshToken.java
  src/main/java/sopt/org/HMH/global/auth/redis/TokenRepository.java
  src/main/java/sopt/org/HMH/global/auth/security/CustomJwtAuthenticationEntryPoint.java
  src/main/java/sopt/org/HMH/global/auth/security/JwtAuthenticationFilter.java
  src/main/java/sopt/org/HMH/global/auth/security/UserAuthentication.java
  src/main/java/sopt/org/HMH/global/auth/social/SocialPlatform.java
  src/main/java/sopt/org/HMH/global/auth/social/kakao/fegin/KakaoApiClient.java
  src/main/java/sopt/org/HMH/global/auth/social/kakao/fegin/KakaoLoginService.java
  src/main/java/sopt/org/HMH/global/auth/social/kakao/response/KakaoAccessTokenResponse.java
  src/main/java/sopt/org/HMH/global/auth/social/kakao/response/KakaoAccount.java
  src/main/java/sopt/org/HMH/global/auth/social/kakao/response/KakaoUserProfile.java
  src/main/java/sopt/org/HMH/global/auth/social/kakao/response/KakaoUserResponse.java
  src/main/java/sopt/org/HMH/global/common/config/JpaAuditingConfig.java
  src/main/java/sopt/org/HMH/global/common/domain/BaseTimeEntity.java
  src/main/java/sopt/org/HMH/global/common/exception/GlobalError.java
  src/main/java/sopt/org/HMH/global/common/exception/GlobalSuccess.java
  src/main/java/sopt/org/HMH/global/common/exception/base/ErrorBase.java
  src/main/java/sopt/org/HMH/global/common/exception/base/ExceptionBase.java
  src/main/java/sopt/org/HMH/global/common/exception/base/SuccessBase.java
  src/main/java/sopt/org/HMH/global/common/response/ApiResponse.java
  src/main/java/sopt/org/HMH/global/common/response/CommonControllerAdvice.java
  src/main/java/sopt/org/HMH/global/common/response/EmptyJsonResponse.java
  src/main/java/sopt/org/HMH/global/config/JpaAuditingConfig.java
  src/main/java/sopt/org/HMH/global/config/RedisConfig.java
  src/main/java/sopt/org/HMH/global/config/SecurityConfig.java
  src/main/java/sopt/org/HMH/global/config/WebConfig.java
Labels: ✨ Feat, 👨🏻‍💻 승환, 🔥 Pull Request

#21 feat - 회원가입 기능 구현
  src/main/java/sopt/org/HMH/domain/challenge/dto/request/ChallengeRequest.java
  src/main/java/sopt/org/HMH/domain/user/controller/UserController.java
  src/main/java/sopt/org/HMH/domain/user/domain/OnboardingInfo.java
  src/main/java/sopt/org/HMH/domain/user/domain/OnboardingProblem.java
  src/main/java/sopt/org/HMH/domain/user/domain/User.java
  src/main/java/sopt/org/HMH/domain/user/domain/exception/UserError.java
  src/main/java/sopt/org/HMH/domain/user/domain/exception/UserSuccess.java
  src/main/java/sopt/org/HMH/domain/user/dto/request/OnboardingRequest.java
  src/main/java/sopt/org/HMH/domain/user/dto/request/SocialPlatformRequest.java
  src/main/java/sopt/org/HMH/domain/user/dto/request/SocialSignUpRequest.java
  src/main/java/sopt/org/HMH/domain/user/repository/OnboardingInfoRepository.java
  src/main/java/sopt/org/HMH/domain/user/repository/UserRepository.java
  src/main/java/sopt/org/HMH/domain/user/service/UserService.java
  src/main/java/sopt/org/HMH/global/auth/social/kakao/fegin/KakaoApiClient.java
  src/main/java/sopt/org/HMH/global/auth/social/kakao/fegin/KakaoLoginService.java
  src/main/java/sopt/org/HMH/global/auth/social/kakao/request/KakaoAccount.java
  src/main/java/sopt/org/HMH/global/auth/social/kakao/request/KakaoUserProfile.java
  src/main/java/sopt/org/HMH/global/auth/social/kakao/request/KakaoUserRequest.java
  src/main/java/sopt/org/HMH/global/auth/social/kakao/response/KakaoAccessTokenResponse.java
  src/main/java/sopt/org/HMH/global/common/Util.java
  src/main/java/sopt/org/HMH/global/config/SecurityConfig.java
Labels: ✨ Feat, 👨🏻‍💻 승환, 🔥 Pull Request

#31 chore - dayChallenge 네이밍 변경
  src/main/java/sopt/org/HMH/domain/app/domain/App.java
  src/main/java/sopt/org/HMH/domain/app/service/AppService.java
  src/main/java/sopt/org/HMH/domain/challenge/domain/Challenge.java
  src/main/java/sopt/org/HMH/domain/challenge/service/ChallengeService.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/domain/DailyChallenge.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/domain/exception/DailyChallengeError.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/repository/DailyChallengeRepository.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/service/DailyChallengeService.java
  src/main/java/sopt/org/HMH/domain/dayChallenge/repository/DayChallengeRepository.java
  src/main/java/sopt/org/HMH/domain/dayChallenge/service/DayChallengeService.java
Labels: 🧹 Chore, 👨🏻‍💻 승환, 🔥 Pull Request

#35 refactor - user와의 필요없는 연관관계 삭제
  src/main/java/sopt/org/HMH/domain/app/domain/App.java
  src/main/java/sopt/org/HMH/domain/challenge/domain/Challenge.java
  src/main/java/sopt/org/HMH/domain/challenge/service/ChallengeService.java
  src/main/java/sopt/org/HMH/domain/user/domain/OnboardingInfo.java
  src/main/java/sopt/org/HMH/domain/user/domain/OnboardingProblem.java
  src/main/java/sopt/org/HMH/domain/user/domain/User.java
  src/main/java/sopt/org/HMH/domain/user/service/UserService.java
Labels: 👩🏻‍💻 주민, 🔨 Refactor

#39 hotfix - codedeploy 스크립트 오류 해결
  script/start.sh
Labels: 🚀 Deploy, 👨🏻‍💻 승환, 🚨 Hotfix, 🔥 Pull Request

#37 feat - 홈 이용통계 불러오기 구현
  src/main/java/sopt/org/HMH/domain/app/controller/AppController.java
  src/main/java/sopt/org/HMH/domain/app/dto/response/AppGoalTimeResponse.java
  src/main/java/sopt/org/HMH/domain/app/service/AppService.java
  src/main/java/sopt/org/HMH/domain/challenge/controller/ChallengeController.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/controller/DailyChallengeController.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/domain/DailyChallenge.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/domain/Status.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/domain/exception/DailyChallengeSuccess.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/dto/response/DailyChallengeResponse.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/service/DailyChallengeService.java
  src/main/java/sopt/org/HMH/domain/user/controller/UserController.java
  src/main/java/sopt/org/HMH/global/common/UserIdConvertor.java
  src/main/java/sopt/org/HMH/global/util/IdConverter.java
Labels: 🪄 API, ✨ Feat, 👩🏻‍💻 주민

#49 hotfix - ApiResponse 필드 code 변경
  src/main/java/sopt/org/HMH/global/common/response/ApiResponse.java
Labels: 🧹 Chore, 👨🏻‍💻 승환, 🚨 Hotfix, 🔥 Pull Request

#44 feat - swagger config 설정
  build.gradle
  src/main/java/sopt/org/HMH/HealthCheckApiController.java
  src/main/java/sopt/org/HMH/global/config/SwaggerConfig.java
Labels: ✨ Feat, 👨🏻‍💻 승환, 📃 Docs, 🔥 Pull Request

#46 feat - 회원 탈퇴 soft delete 구현
  src/main/java/sopt/org/HMH/domain/app/domain/exception/AppSuccess.java
  src/main/java/sopt/org/HMH/domain/challenge/domain/exception/ChallengeError.java
  src/main/java/sopt/org/HMH/domain/challenge/domain/exception/ChallengeSuccess.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/domain/exception/DailyChallengeError.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/domain/exception/DailyChallengeSuccess.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/repository/DailyChallengeRepository.java
  src/main/java/sopt/org/HMH/domain/user/controller/UserController.java
  src/main/java/sopt/org/HMH/domain/user/domain/User.java
  src/main/java/sopt/org/HMH/domain/user/domain/exception/UserError.java
  src/main/java/sopt/org/HMH/domain/user/domain/exception/UserSuccess.java
  src/main/java/sopt/org/HMH/domain/user/repository/UserRepository.java
  src/main/java/sopt/org/HMH/domain/user/service/ExpiredUserDeleteBatch.java
  src/main/java/sopt/org/HMH/domain/user/service/UserService.java
  src/main/java/sopt/org/HMH/global/HealthCheckApiController.java
  src/main/java/sopt/org/HMH/global/common/constant/PointConstants.java
Labels: 🪄 API, ✨ Feat, 👨🏻‍💻 승환, 🔥 Pull Request

#45 feat - 일별 챌린지 실패 처리 기능 구현
  src/main/java/sopt/org/HMH/domain/app/repository/AppRepository.java
  src/main/java/sopt/org/HMH/domain/challenge/domain/Challenge.java
  src/main/java/sopt/org/HMH/domain/challenge/repository/ChallengeRepository.java
  src/main/java/sopt/org/HMH/domain/challenge/service/ChallengeService.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/controller/DailyChallengeController.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/domain/DailyChallenge.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/domain/exception/DailyChallengeSuccess.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/service/DailyChallengeService.java
Labels: 🪄 API, ✨ Feat, 👨🏻‍💻 승환, 🔥 Pull Request

#50 feat - 달성현황 정보 불러오기
  src/main/java/sopt/org/HMH/domain/app/dto/response/AppGoalTimeResponse.java
  src/main/java/sopt/org/HMH/domain/app/service/AppService.java
  src/main/java/sopt/org/HMH/domain/challenge/controller/ChallengeController.java
  src/main/java/sopt/org/HMH/domain/challenge/domain/exception/ChallengeSuccess.java
  src/main/java/sopt/org/HMH/domain/challenge/dto/response/ChallengeResponse.java
  src/main/java/sopt/org/HMH/domain/challenge/service/ChallengeService.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/controller/DailyChallengeController.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/dto/response/DailyChallengeResponse.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/service/DailyChallengeService.java
  src/main/java/sopt/org/HMH/global/util/IdConverter.java
Labels: 🪄 API, ✨ Feat, 👩🏻‍💻 주민

#56 feat - 챌린지 상태 정보 업데이트
  src/main/java/sopt/org/HMH/domain/app/domain/App.java
  src/main/java/sopt/org/HMH/domain/app/dto/request/AppArrayUsageTimeRequest.java
  src/main/java/sopt/org/HMH/domain/app/dto/request/AppUsageTimeRequest.java
  src/main/java/sopt/org/HMH/domain/app/service/AppService.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/controller/DailyChallengeController.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/domain/DailyChallenge.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/domain/exception/DailyChallengeSuccess.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/service/DailyChallengeService.java
Labels: 🪄 API, ✨ Feat, 👩🏻‍💻 주민

#61 스프링에서 redis 비밀번호를 통해 접근할 수 있도록 수정
  src/main/java/sopt/org/HMH/global/config/RedisConfig.java
Labels: 👨🏻‍💻 승환, 🐞 BugFix, 🔥 Pull Request

#64 fix - 날짜 차이 구하는 로직 오류 해결
  src/main/java/sopt/org/HMH/domain/dailychallenge/service/DailyChallengeService.java
Labels: 🐞 BugFix, 🚨 Hotfix, 🔥 Pull Request

#57 feat - 인증 인가 에러 로직 변경 및 에러 validator 추가
  src/main/java/sopt/org/HMH/domain/app/controller/AppController.java
  src/main/java/sopt/org/HMH/domain/app/service/AppService.java
  src/main/java/sopt/org/HMH/domain/challenge/controller/ChallengeController.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/controller/DailyChallengeController.java
  src/main/java/sopt/org/HMH/domain/user/controller/UserController.java
  src/main/java/sopt/org/HMH/domain/user/domain/OnboardingInfo.java
  src/main/java/sopt/org/HMH/domain/user/domain/User.java
  src/main/java/sopt/org/HMH/domain/user/domain/UserConstants.java
  src/main/java/sopt/org/HMH/domain/user/service/ExpiredUserDeleteScheduler.java
  src/main/java/sopt/org/HMH/domain/user/service/UserService.java
  src/main/java/sopt/org/HMH/global/auth/UserId.java
  src/main/java/sopt/org/HMH/global/auth/UserIdArgumentResolver.java
  src/main/java/sopt/org/HMH/global/auth/jwt/JwtConstants.java
  src/main/java/sopt/org/HMH/global/auth/jwt/JwtGenerator.java
  src/main/java/sopt/org/HMH/global/auth/jwt/JwtProvider.java
  src/main/java/sopt/org/HMH/global/auth/jwt/JwtValidator.java
  src/main/java/sopt/org/HMH/global/auth/jwt/exception/JwtError.java
  src/main/java/sopt/org/HMH/global/auth/redis/RefreshToken.java
  src/main/java/sopt/org/HMH/global/auth/redis/TokenService.java
  src/main/java/sopt/org/HMH/global/auth/security/JwtAuthenticationEntryPoint.java
  src/main/java/sopt/org/HMH/global/auth/security/JwtAuthenticationFilter.java
  src/main/java/sopt/org/HMH/global/auth/security/UserAuthentication.java
  src/main/java/sopt/org/HMH/global/auth/security/exception/ExceptionHandlerFilter.java
  src/main/java/sopt/org/HMH/global/auth/social/kakao/fegin/KakaoLoginService.java
  src/main/java/sopt/org/HMH/global/common/constant/PointConstants.java
  src/main/java/sopt/org/HMH/global/common/response/CommonControllerAdvice.java
  src/main/java/sopt/org/HMH/global/config/SecurityConfig.java
  src/main/java/sopt/org/HMH/global/config/WebConfig.java
  src/main/java/sopt/org/HMH/global/util/IdConverter.java
Labels: ✨ Feat, 👨🏻‍💻 승환, 🔥 Pull Request, 🔨 Refactor

#62 fix - Schedular를 통해 삭제되어야 할 유저가 삭제되지 않는 문제 해결
  src/main/java/sopt/org/HMH/domain/user/repository/UserRepository.java
  src/main/java/sopt/org/HMH/global/config/SchedulerConfig.java
Labels: 👨🏻‍💻 승환, 🐞 BugFix, 🔥 Pull Request

#59 feat - 챌린지 생성 api 수정
  src/main/java/sopt/org/HMH/domain/app/controller/AppController.java
  src/main/java/sopt/org/HMH/domain/app/dto/request/AppGoalTimeRequest.java
  src/main/java/sopt/org/HMH/domain/app/dto/response/AppGoalTimeResponse.java
  src/main/java/sopt/org/HMH/domain/app/service/AppService.java
  src/main/java/sopt/org/HMH/domain/challenge/controller/ChallengeController.java
  src/main/java/sopt/org/HMH/domain/challenge/dto/request/ChallengeRequest.java
  src/main/java/sopt/org/HMH/domain/challenge/dto/response/AddChallengeResponse.java
  src/main/java/sopt/org/HMH/domain/challenge/dto/response/ChallengeResponse.java
  src/main/java/sopt/org/HMH/domain/challenge/service/ChallengeService.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/dto/response/DailyChallengeResponse.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/service/DailyChallengeService.java
  src/main/java/sopt/org/HMH/domain/user/service/UserService.java
Labels: 🪄 API, 👩🏻‍💻 주민, 🔧 Modify

#66 fix - swagger 오류 수정
  src/main/java/sopt/org/HMH/global/config/SecurityConfig.java
Labels: 👩🏻‍💻 주민, 🐞 BugFix

#70 fix - 앱 추가 삭제 오류 수정
  src/main/java/sopt/org/HMH/domain/app/controller/AppController.java
  src/main/java/sopt/org/HMH/domain/app/service/AppService.java
  src/main/java/sopt/org/HMH/domain/challenge/service/ChallengeService.java
  src/main/java/sopt/org/HMH/domain/user/service/UserService.java
Labels: 🪄 API, 👩🏻‍💻 주민, 🐞 BugFix

#72 docs - #71 readme 수정
  README.md
Labels: 👨🏻‍💻 승환, 📃 Docs, 🔥 Pull Request

#80 feat - 챌린지 관련 컨트롤러들 swagger 연결
  src/main/java/sopt/org/HMH/domain/app/controller/AppApi.java
  src/main/java/sopt/org/HMH/domain/app/controller/AppController.java
  src/main/java/sopt/org/HMH/domain/challenge/controller/ChallengeApi.java
  src/main/java/sopt/org/HMH/domain/challenge/controller/ChallengeController.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/controller/DailyChallengeApi.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/controller/DailyChallengeController.java
  src/main/java/sopt/org/HMH/domain/user/controller/UserController.java
  src/main/java/sopt/org/HMH/global/auth/security/JwtAuthenticationEntryPoint.java
  src/main/java/sopt/org/HMH/global/auth/security/exception/ExceptionHandlerFilter.java
  src/main/java/sopt/org/HMH/global/common/response/ApiResponse.java
  src/main/java/sopt/org/HMH/global/common/response/BaseResponse.java
  src/main/java/sopt/org/HMH/global/common/response/CommonControllerAdvice.java
Labels: ✨ Feat, 👩🏻‍💻 주민, 📃 Docs, 🔥 Pull Request

#75 feat - 더미 앱 생성 api 구현
  src/main/java/sopt/org/HMH/domain/dummy/DummyApp.java
  src/main/java/sopt/org/HMH/domain/dummy/DummyAppController.java
  src/main/java/sopt/org/HMH/domain/dummy/DummyAppListResponse.java
  src/main/java/sopt/org/HMH/domain/dummy/DummyAppSuccess.java
  src/main/java/sopt/org/HMH/global/config/SecurityConfig.java
Labels: ✨ Feat, 👨🏻‍💻 승환, 🔥 Pull Request

#78 fix - 회원 가입시 문제 인식 정보 입력되지 않는 오류 해결
  src/main/java/sopt/org/HMH/domain/challenge/dto/response/ChallengeResponse.java
  src/main/java/sopt/org/HMH/domain/dummy/DummyAppController.java
  src/main/java/sopt/org/HMH/domain/user/domain/User.java
  src/main/java/sopt/org/HMH/domain/user/repository/ProblemRepository.java
  src/main/java/sopt/org/HMH/domain/user/service/UserService.java
Labels: 👨🏻‍💻 승환, 🐞 BugFix, 🔥 Pull Request

#84 feat - 챌린지 관련 유효성 체크
  src/main/java/sopt/org/HMH/domain/challenge/domain/ChallengeConstants.java
  src/main/java/sopt/org/HMH/domain/challenge/domain/ChallengeDay.java
  src/main/java/sopt/org/HMH/domain/challenge/domain/exception/ChallengeError.java
  src/main/java/sopt/org/HMH/domain/challenge/repository/ChallengeRepository.java
  src/main/java/sopt/org/HMH/domain/challenge/service/ChallengeService.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/service/DailyChallengeService.java
Labels: ✨ Feat, 👩🏻‍💻 주민, 🔥 Pull Request

#87 modify - 더미 데이터 반환값에 목표 시간 및 사용 시간 추가
  src/main/java/sopt/org/HMH/domain/dummy/DummyApp.java
  src/main/java/sopt/org/HMH/domain/dummy/DummyAppListResponse.java
Labels: 👨🏻‍💻 승환, 🔧 Modify, 🔥 Pull Request

#89 fix - 홈 이용시간 통계 불러오기 오류 해결
  src/main/java/sopt/org/HMH/domain/challenge/repository/ChallengeRepository.java
  src/main/java/sopt/org/HMH/domain/challenge/service/ChallengeService.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/service/DailyChallengeService.java
Labels: 👨🏻‍💻 승환, 🐞 BugFix, 🔥 Pull Request

#90 feat - 유저 관련 Swagger 기능 추가
  src/main/java/sopt/org/HMH/domain/app/controller/AppApi.java
  src/main/java/sopt/org/HMH/domain/challenge/controller/ChallengeApi.java
  src/main/java/sopt/org/HMH/domain/challenge/controller/ChallengeController.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/controller/DailyChallengeApi.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/controller/DailyChallengeController.java
  src/main/java/sopt/org/HMH/domain/user/controller/UserApi.java
  src/main/java/sopt/org/HMH/domain/user/controller/UserController.java
  src/main/java/sopt/org/HMH/global/common/exception/CommonControllerAdvice.java
  src/main/java/sopt/org/HMH/global/config/SwaggerConfig.java
Labels: ✨ Feat, 👨🏻‍💻 승환, 📃 Docs, 🔥 Pull Request

#93 fix - #92 날짜 수정
  src/main/java/sopt/org/HMH/domain/challenge/dto/response/ChallengeResponse.java
Labels: 👩🏻‍💻 주민, 🐞 BugFix, 🚨 Hotfix, 🔥 Pull Request

#94 fix - 회원 탈퇴시 연관된 challenge, dailychallenge, app 삭제 기능 구현
  src/main/java/sopt/org/HMH/domain/challenge/domain/Challenge.java
  src/main/java/sopt/org/HMH/domain/challenge/repository/ChallengeRepository.java
  src/main/java/sopt/org/HMH/domain/challenge/service/ChallengeService.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/domain/DailyChallenge.java
  src/main/java/sopt/org/HMH/domain/user/repository/UserRepository.java
  src/main/java/sopt/org/HMH/domain/user/service/ExpiredUserDeleteScheduler.java
  src/main/java/sopt/org/HMH/domain/user/service/UserService.java
Labels: 👨🏻‍💻 승환, 🐞 BugFix, 🔥 Pull Request

#95 feat - 앱 관련 유효성 체크
  src/main/java/sopt/org/HMH/domain/app/domain/AppConstants.java
  src/main/java/sopt/org/HMH/domain/app/domain/exception/AppError.java
  src/main/java/sopt/org/HMH/domain/app/domain/exception/AppException.java
  src/main/java/sopt/org/HMH/domain/app/repository/AppRepository.java
  src/main/java/sopt/org/HMH/domain/app/service/AppService.java
  src/main/java/sopt/org/HMH/domain/dailychallenge/service/DailyChallengeService.java
Labels: ✨ Feat, 👩🏻‍💻 주민, 🔥 Pull Request
