Repository Team-HMH/HMH-Server, pull requests merged in 2024-07, with the labels that each got.

#172 feat: admin api 추가
  src/main/java/sopt/org/hmh/domain/admin/controller/AdminApi.java
  src/main/java/sopt/org/hmh/domain/admin/controller/AdminController.java
  src/main/java/sopt/org/hmh/domain/admin/dto/request/AdminDailyChallengeRequest.java
  src/main/java/sopt/org/hmh/domain/admin/dto/request/AdminLoginRequest.java
  src/main/java/sopt/org/hmh/domain/admin/dto/request/AdminUserIdRequest.java
  src/main/java/sopt/org/hmh/domain/admin/dto/request/AdminUserInfoRequest.java
  src/main/java/sopt/org/hmh/domain/admin/dto/response/AdminTokenResponse.java
  src/main/java/sopt/org/hmh/domain/admin/exception/AdminError.java
  src/main/java/sopt/org/hmh/domain/admin/exception/AdminException.java
  src/main/java/sopt/org/hmh/domain/admin/exception/AdminSuccess.java
  src/main/java/sopt/org/hmh/domain/admin/service/AdminFacade.java
  src/main/java/sopt/org/hmh/domain/auth/service/AuthFacade.java
  src/main/java/sopt/org/hmh/domain/challenge/controller/ChallengeController.java
  src/main/java/sopt/org/hmh/domain/challenge/repository/ChallengeRepository.java
  src/main/java/sopt/org/hmh/domain/challenge/service/ChallengeService.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/domain/DailyChallenge.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/repository/DailyChallengeRepository.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/service/DailyChallengeFacade.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/service/DailyChallengeService.java
  src/main/java/sopt/org/hmh/domain/user/domain/User.java
  src/main/java/sopt/org/hmh/domain/user/service/ExpiredUserDeleteScheduler.java
  src/main/java/sopt/org/hmh/domain/user/service/UserService.java
  src/main/java/sopt/org/hmh/global/auth/UserIdArgumentResolver.java
  src/main/java/sopt/org/hmh/global/auth/jwt/JwtConstants.java
  src/main/java/sopt/org/hmh/global/auth/jwt/JwtGenerator.java
  src/main/java/sopt/org/hmh/global/auth/jwt/JwtPrefixExtractor.java
  src/main/java/sopt/org/hmh/global/auth/jwt/JwtProvider.java
  src/main/java/sopt/org/hmh/global/auth/jwt/JwtValidator.java
  src/main/java/sopt/org/hmh/global/auth/jwt/TokenService.java
  src/main/java/sopt/org/hmh/global/auth/jwt/exception/JwtError.java
  src/main/java/sopt/org/hmh/global/auth/security/JwtAuthenticationFilter.java
  src/main/java/sopt/org/hmh/global/auth/security/UserAuthentication.java
  src/main/java/sopt/org/hmh/global/auth/security/ValidateAdminInterceptor.java
  src/main/java/sopt/org/hmh/global/config/SecurityConfig.java
  src/main/java/sopt/org/hmh/global/config/WebConfig.java
Labels: ✨ Feat

#176 fix - Optional 안에 null이 들어갈 수 있도록 코드를 변경하여 NPE 방지
  src/main/java/sopt/org/hmh/domain/challenge/service/ChallengeFacade.java
Labels: 🐞 BugFix

#177 hotfix - 회원가입시 NPE 발생 이슈
  src/main/java/sopt/org/hmh/domain/challenge/service/ChallengeFacade.java
Labels: 🚨 Hotfix

#180 fix - @EnableWebMvc 제거로 예상하지 않은 기능이 구현되지 않도록 수정
  src/main/java/sopt/org/hmh/global/config/WebConfig.java
Labels: 🐞 BugFix

#178 refactor - AuthFacade 관련 코드 리팩토링
  .gitignore
  build.gradle
  src/main/java/sopt/org/hmh/domain/app/repository/ChallengeAppRepository.java
  src/main/java/sopt/org/hmh/domain/app/repository/HistoryAppRepository.java
  src/main/java/sopt/org/hmh/domain/app/repository/challenge_app/ChallengeAppJpaRepository.java
  src/main/java/sopt/org/hmh/domain/app/repository/challenge_app/ChallengeAppRepository.java
  src/main/java/sopt/org/hmh/domain/app/repository/challenge_app/ChallengeAppRepositoryImpl.java
  src/main/java/sopt/org/hmh/domain/app/service/ChallengeAppService.java
  src/main/java/sopt/org/hmh/domain/auth/controller/AuthController.java
  src/main/java/sopt/org/hmh/domain/auth/dto/request/SocialSignUpRequest.java
  src/main/java/sopt/org/hmh/domain/auth/service/AuthFacade.java
  src/main/java/sopt/org/hmh/domain/challenge/controller/ChallengeController.java
  src/main/java/sopt/org/hmh/domain/challenge/domain/exception/ChallengeError.java
  src/main/java/sopt/org/hmh/domain/challenge/dto/request/ChallengeSignUpRequest.java
  src/main/java/sopt/org/hmh/domain/challenge/service/ChallengeFacade.java
  src/main/java/sopt/org/hmh/domain/challenge/service/ChallengeService.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/service/DailyChallengeService.java
  src/main/java/sopt/org/hmh/domain/user/service/UserService.java
Labels: 🔨 Refactor

#181 hotfix - LocalDate가 배열로 오는 문제 해결 main hot fix
  .gitignore
  build.gradle
  src/main/java/sopt/org/hmh/domain/app/repository/ChallengeAppRepository.java
  src/main/java/sopt/org/hmh/domain/app/repository/HistoryAppRepository.java
  src/main/java/sopt/org/hmh/domain/app/repository/challenge_app/ChallengeAppJpaRepository.java
  src/main/java/sopt/org/hmh/domain/app/repository/challenge_app/ChallengeAppRepository.java
  src/main/java/sopt/org/hmh/domain/app/repository/challenge_app/ChallengeAppRepositoryImpl.java
  src/main/java/sopt/org/hmh/domain/app/service/ChallengeAppService.java
  src/main/java/sopt/org/hmh/domain/auth/controller/AuthController.java
  src/main/java/sopt/org/hmh/domain/auth/dto/request/SocialSignUpRequest.java
  src/main/java/sopt/org/hmh/domain/auth/service/AuthFacade.java
  src/main/java/sopt/org/hmh/domain/challenge/controller/ChallengeController.java
  src/main/java/sopt/org/hmh/domain/challenge/domain/exception/ChallengeError.java
  src/main/java/sopt/org/hmh/domain/challenge/dto/request/ChallengeSignUpRequest.java
  src/main/java/sopt/org/hmh/domain/challenge/service/ChallengeFacade.java
  src/main/java/sopt/org/hmh/domain/challenge/service/ChallengeService.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/service/DailyChallengeService.java
  src/main/java/sopt/org/hmh/domain/user/service/UserService.java
  src/main/java/sopt/org/hmh/global/config/WebConfig.java
Labels: 🚨 Hotfix

#185 fix - 챌린지 생성 시 중복된 일별 챌린지를 생성하지 않도록 유효성 검사 로직 추가
  src/main/java/sopt/org/hmh/domain/dailychallenge/domain/exception/DailyChallengeError.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/repository/DailyChallengeRepository.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/repository/DailyChallengeRepositoryImpl.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/service/DailyChallengeService.java
Labels: 🐞 BugFix, 🔧 Modify

#184 modify - 일별챌린지 결과 전송 후 챌린지의 변경된 상태값들을 반환하도록 수정
  src/main/java/sopt/org/hmh/domain/challenge/domain/Challenge.java
  src/main/java/sopt/org/hmh/domain/challenge/dto/response/ChallengeResponse.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/controller/DailyChallengeApi.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/controller/DailyChallengeController.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/dto/response/ChallengeStatusesResponse.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/repository/DailyChallengeJpaRepository.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/repository/DailyChallengeRepository.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/repository/DailyChallengeRepositoryImpl.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/service/DailyChallengeFacade.java
  src/main/java/sopt/org/hmh/domain/dailychallenge/service/DailyChallengeService.java
Labels: 👩🏻‍💻 주민, 🔧 Modify
